To use https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs[Azure Monitor Logs], add the following dependency to your project:

dependency:io.micronaut.azure:micronaut-azure-logging[]

=== Create Azure Logging Resources

Refer to the https://guides.micronaut.io/latest/micronaut-azure-logging.html[Micronaut Azure Logging guide] for information about creating the required Azure resources.

=== Application configuration

There are three application configuration properties required to configure the Logback appender that pushes Logback log events to Azure Monitor Logs.
In addition, you can enable or disable the appender, which defaults to being enabled.



.Azure Logging Configuration Properties
|===
|Property|Type|Required|Default value|Description

|`azure.logging.enabled`
|`boolean`
|`false`
|`true`
|Whether the Logback appender is enabled

|`azure.logging.data-collection-endpoint`
|`String`
|`true`
|_none_
|Azure Monitor data collection endpoint URL

|`azure.logging.rule-id`
|`String`
|`true`
|_none_
|The Azure Monitor data collection rule id that is configured to collect and transform the logs

|`azure.logging.stream-name`
|`String`
|`true`
|_none_
|The Azure Monitor stream name configured in the data collection rule, for example a table in a Log Analytics workspace
|===

=== Logback configuration

Edit your `src/main/resources/logback.xml` file to look like this:

.src/main/resources/logback.xml
[source,xml]
----
<configuration>

    <appender name='AZURE' class='io.micronaut.azure.logging.AzureAppender'>
        <!-- <blackListLoggerName>example.app.Application</blackListLoggerName> -->
        <encoder class='ch.qos.logback.core.encoder.LayoutWrappingEncoder'>
            <layout class='ch.qos.logback.contrib.json.classic.JsonLayout'>
                <jsonFormatter class='io.micronaut.azure.logging.AzureJsonFormatter' />
            </layout>
        </encoder>
    </appender>

    <root level='INFO'>
        <appender-ref ref='AZURE' />
    </root>

</configuration>
----

You can customize your JsonLayout with additional parameters that are described in the Logback https://javadoc.io/static/ch.qos.logback.contrib/logback-json-classic/0.1.5/ch/qos/logback/contrib/json/classic/JsonLayout.html[JsonLayout] documentation.

The `AzureAppender` supports blacklisting loggers by specifying the logger name(s) to exclude in `blackListLoggerName` elements.

.Configurable AzureAppender Appender Properties
|===
|Property|Type|Required|Default value|Description

|`subject`
|`String`
|false
|application-name
|the subject of the log

|`source`
|`String`
|false
|host-name
|the source of the log

|`publishPeriod`
|`Integer`
|false
|100
|Time in ms between two batch publishing of logs

|`maxBatchSize`
|`Integer`
|false
|128
|The maximum number of log events that will be sent in one batch request

|`queueSize`
|`Integer`
|false
|128
|The size of publishing log queue

|`blackListLoggerName`
|`String`
|false
|_none_
|Logger name(s) that will be excluded
|===

=== Emergency Appender

Since the Azure appender queues log messages and then writes them remotely, there are situations which might result in log events not getting remoted correctly.
To address such scenarios you can configure the emergency appender to preserve those messages.

Configure an appender element in your `src/main/resources/logback.xml`; in the example it is `STDOUT`, but any valid Logback appender can be used.
Inside the `AzureAppender` element, add an `appender-ref` element that references the emergency appender.

.src/main/resources/logback.xml
[source,xml]
----
<configuration>

    <appender name='STDOUT' class='ch.qos.logback.core.ConsoleAppender'>
        <encoder>
            <pattern>%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name='AZURE' class='io.micronaut.azure.logging.AzureAppender'>
        <appender-ref ref='STDOUT'/>
        <blackListLoggerName>org.apache.http.impl.conn.PoolingHttpClientConnectionManager</blackListLoggerName>
        <encoder class='ch.qos.logback.core.encoder.LayoutWrappingEncoder'>
            <layout class='ch.qos.logback.contrib.json.classic.JsonLayout'>
                <jsonFormatter class='io.micronaut.azure.logging.AzureJsonFormatter' />
            </layout>
        </encoder>
    </appender>

    <root level='INFO'>
        <appender-ref ref='AZURE' />
    </root>

</configuration>
----

=== Browsing the logs

Refer to the https://guides.micronaut.io/latest/micronaut-azure-logging.html[Micronaut Azure Logging guide] for how to retrieve log entries published to Azure Monitor Logs.

If you have any troubles with configuring the Azure Appender you can try to add `<configuration debug='false'>` into your Logback configuration.
