The `micronaut-azure-sdk` module supports these authentication options:

=== DefaultAzureCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable[DefaultAzureCredential] is appropriate for most scenarios where the application ultimately runs in the
Azure Cloud. It combines credentials that are commonly used to authenticate when deployed,
with credentials that are used to authenticate in a development environment.

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable[DefaultAzureCredential] is used when no other credential type is specified or explicitly enabled.

=== ClientCertificateCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.clientcertificatecredential?view=azure-java-stable[ClientCertificateCredential] authenticates the created service principal through its client certificate. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth?view=azure-java-stable#client-certificate-credential[Client certificate credential] for more details.

The ClientCertificateCredential supports both PFX and PEM certificate file types.

.Use of PEM certificate
[source,yaml]
----
azure:
  credential:
    client-certificate:
      client-id: <client-id>
      pem-certificate-path: <path to pem certificate>
----

.Use of PFX certificate
[source,yaml]
----
azure:
  credential:
    client-certificate:
      client-id: <client-id>
      pfx-certificate-path: <path to pfx certificate>
      pfx-certificate-password: <pfx certificate password>
----

Optionally you can configure the tenant id by setting the property `azure.credential.client-certificate.tenant-id`.

=== ClientSecretCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.clientsecretcredential?view=azure-java-stable[ClientSecretCredential]  authenticates the created service principal through its client secret (password). See more on https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth?view=azure-java-stable#client-secret-credential[Client secret credential] for more details.

.Use of client secret credential
[source,yaml]
----
azure:
  credential:
    client-secret:
      client-id: <client-id>
      tenant-id: <tenant-id>
      secret: <secret>
----

=== UsernamePasswordCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.usernamepasswordcredential?view=azure-java-stable[UsernamePasswordCredential] helps to authenticate a public client application using the user credentials that don't require multi-factor authentication. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-user-auth?view=azure-java-stable#username-password-credential[Username password credential] for more details.

.Use of username password credential
[source,yaml]
----
azure:
  credential:
    username-password:
      client-id: <client-id>
      username: <username>
      password: <password>
----

Optionally you can configure the tenant id by setting the property `azure.credential.username-password.tenant-id`.

=== ManagedIdentityCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.managedidentitycredential?view=azure-java-stable[ManagedIdentityCredential] authenticates the managed identity (system or user assigned) of an Azure resource. So, if the application is running inside an Azure resource that supports Managed Identity through IDENTITY/MSI, IMDS endpoints, or both, then this credential will get your application authenticated, and offers a great secretless authentication experience. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-azure-hosted-auth?view=azure-java-stable#managed-identity-credential[Managed Identity credential] for more details.

.Example on how to enable the managed identity credential for system assigned identity
[source,yaml]
----
azure:
  credential:
    managed-identity:
      enabled: true
----

Note, that for user-assigned identity you have to also set the `azure.credential.managed-identity.client-id`.

=== AzureCliCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.azureclicredential?view=azure-java-stable[AzureCliCredential] authenticates in a development environment with the enabled user or service principal in Azure CLI. It uses the Azure CLI given a user that is already logged into it, and uses the CLI to authenticate the application against Azure Active Directory. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth?view=azure-java-stable#azure-cli-credential[Azure CLI credential] for more details.

.Example on how to enable the azure credential
[source,yaml]
----
azure:
  credential:
    cli:
      enabled: true
----

=== IntelliJCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.intellijcredential?view=azure-java-stable[IntelliJCredential] authenticates in a development environment with the account in Azure Toolkit for IntelliJ. It uses the logged in user information on the IntelliJ IDE and uses it to authenticate the application against Azure Active Directory. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth?view=azure-java-stable#intellij-credential[IntelliJ credential] for more details.

.Example on how to enable the azure credential
[source,yaml]
----
azure:
  credential:
    intellij:
      enabled: true
----

Note, that for Windows platform the KeePass database path needs to be set by property `azure.credential.intellij.kee-pass-database-path`. The KeePass database path is used to read the cached credentials of Azure toolkit for IntelliJ plugin. For macOS and Linux platform native key chain / key ring will be accessed respectively to retrieve the cached credentials.

Optionally you can configure the tenant id by setting the property `azure.credential.intellij.tenant-id`.

=== VisualStudioCodeCredential

The https://docs.microsoft.com/en-us/java/api/com.azure.identity.visualstudiocodecredential?view=azure-java-stable[VisualStudioCodeCredential] enables authentication in development environments where VS Code is installed with the VS Code Azure Account extension. It uses the logged-in user information in the VS Code IDE and uses it to authenticate the application against Azure Active Directory. Visit https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth?view=azure-java-stable#visual-studio-code-credential[Visual Studio Code credential] for more details.

.Example on how to enable the visual studio code credential
[source,yaml]
----
azure:
  credential:
    visual-studio-code:
      enabled: true
----

Optionally you can configure the tenant id by setting the property `azure.credential.visual-studio-code.tenant-id`.