plugins {
    id 'io.micronaut.build.internal.azure-module'
}

dependencies {
    annotationProcessor(mn.micronaut.inject.java)
    api(libs.managed.azure.cosmos) {
        exclude group: "io.projectreactor.netty", module: "reactor-netty-http"
    }
    api("io.projectreactor.netty:reactor-netty-http:1.2.8") {
        because("CVE-2025-22227 - older versions leak credentials")
    }
    testCompileOnly(mn.micronaut.inject.groovy)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(platform(mnTestResources.boms.testcontainers))
    testImplementation(libs.testcontainers.azure)

    constraints {
        implementation("io.projectreactor.netty:reactor-netty-http:1.2.8") {
            because("Older versions have CVEs")
        }
    }
}
